[package]
name = "gamesman-nova"
version = "0.1.0"
edition = "2021"
authors = ["Max Fierro <maxfierro@berkeley.edu>"]
description = "System for solving finite, deterministic, complete-information, abstract-strategy games."
license = "	GPL-3.0"
repository = "https://github.com/GamesCrafters/GamesmanNova"
keywords = ["game", "solver", "strong-solver"]
readme = "README.md"
exclude = ["/.github"]

[[bin]]
name = "nova"
path = "src/main.rs"
test = true
bench = true

[dependencies]
clap = { version = "^4", features = ["derive"] }
exitcode = "^1"
strsim = "^0"
serde_json = "^1"
regex = "^1"
nalgebra = "^0"
colored = "^2"
