[package]
name = "gamesman-nova"
version = "0.1.1"
description = "System for computing the solution set of finite, deterministic, complete-information, abstract-strategy games."
authors = ["Max Fierro <maxfierro@berkeley.edu>"]
license = "GPL-3.0"
repository = "https://github.com/GamesCrafters/GamesmanNova"
keywords = ["game", "solver", "strong-solver"]
edition = "2021"
readme = "README.md"
exclude = ["/.github"]

[[bin]]
name = "nova"
path = "src/main.rs"
test = true
bench = true

[profile.release]
# Defaults:
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
panic = 'unwind'
incremental = false
rpath = false

# Modified:
lto = "fat"
codegen-units = 1

[profile.dev]
# Defaults:
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[dependencies]
clap = { version = "^4", features = ["derive"] }
exitcode = "^1"
strsim = "^0"
serde_json = "^1"
regex = "^1"
nalgebra = "^0"
colored = "^2"
