[package]
name = "nova"
version = "0.1.0"
edition = "2021"
description = "System for solving finite, deterministic, complete-information, abstract-strategy games."
license = "	GPL-3.0-or-later"
repository = "https://github.com/GamesCrafters/GamesmanNova"
keywords = ["game", "solver"]

[dependencies]
clap = { version = "^4", features = ["derive"] }
exitcode = "^1"
strsim = "^0"
serde_json = "^1"
regex = "^1"
nalgebra = "^0"
colored = "^2"
