[package]
name = "gamesman-nova"
version = "0.1.5"
description = "System for computing the solution set of finite, deterministic, complete-information, abstract-strategy games."
authors = ["Max Fierro <maxfierro@berkeley.edu>"]
license = "GPL-3.0"
repository = "https://github.com/GamesCrafters/GamesmanNova"
keywords = ["game", "solver", "strong-solver"]
edition = "2021"
readme = "README.md"
exclude = ["/.github"]

[[bin]]
name = "nova"
path = "src/main.rs"
test = true
bench = true

[profile.release]
lto = "fat"
codegen-units = 1
debug = true

[dependencies]
clap = { version = "^4", features = ["derive"] }
exitcode = "^1"
serde_json = "^1"
regex = "^1"
nalgebra = "^0"
colored = "^2"
num-traits = "^0"
