binop_separator = "Front"
brace_style = "AlwaysNextLine"
combine_control_expr = false
max_width = 80
comment_width = 80
doc_comment_code_block_width = 80
fn_call_width = 70
condense_wildcard_suffixes = true
empty_item_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Lower"
imports_indent = "Block"
indent_style = "Block"
reorder_impl_items = true
trailing_semicolon = false
wrap_comments = true
