# PROJECT FORMAT SPECIFICATION
# See https://rust-lang.github.io/rustfmt/

# Stable features
max_width = 80
fn_call_width = 70

# Unstable features (nightly only, tracking issues linked)
binop_separator = "Front"           # https://github.com/rust-lang/rustfmt/issues/3368
brace_style = "AlwaysNextLine"      # https://github.com/rust-lang/rustfmt/issues/3376
combine_control_expr = false        # https://github.com/rust-lang/rustfmt/issues/3369
comment_width = 80                  # https://github.com/rust-lang/rustfmt/issues/3349
doc_comment_code_block_width = 80   # https://github.com/rust-lang/rustfmt/issues/5359
condense_wildcard_suffixes = true   # https://github.com/rust-lang/rustfmt/issues/3384
empty_item_single_line = true       # https://github.com/rust-lang/rustfmt/issues/3356
format_code_in_doc_comments = true  # https://github.com/rust-lang/rustfmt/issues/3348
hex_literal_case = "Lower"          # https://github.com/rust-lang/rustfmt/issues/5081
imports_indent = "Block"            # https://github.com/rust-lang/rustfmt/issues/3360
indent_style = "Block"              # https://github.com/rust-lang/rustfmt/issues/3346
reorder_impl_items = true           # https://github.com/rust-lang/rustfmt/issues/3363
trailing_semicolon = false          # https://github.com/rust-lang/rustfmt/issues/3378
wrap_comments = true                # https://github.com/rust-lang/rustfmt/issues/3347
