[package]
name = "get-session"
version = "0.1.0"
edition = "2021"
description = "A procedural macro for making a GamesmanNova game Session out of a string."
license = "	GPL-3.0-or-later"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[lib]
proc-macro = true
