name: Verify Forced Commit

on: 
  push:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  verify_commit_to_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose
    
    - name: Format Check
      run: cargo fmt --verbose -- --check
