name: Verify and Format

on: 
  push:
    branches:
      - '**'
      - '!main'

env:
  CARGO_TERM_COLOR: always

jobs:
  verify_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose
    
    - name: Format and Commit
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
