name: Verify and Format

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  verify_feature:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose
    
    - name: Format and Commit
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  verify_main:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose
